### ISSUE TITLE
Correzione analisi dei requisiti

### ISSUE THREAD

**Issue by massi94** [SWEetBIT/SWEDesigner---RR#4]
Sistemare le seguenti indicazioni della RR:
- [x] sezione funzionalità del prodotto deve essere ESTESA
- [x] scenario principale sempre riportato nella descrizione dei UC
- [x] UC1.5 aggiungere controlli sui dati inseriti
- [x] UC1.6 aggiungere controlli sui dati inseriti
- [x] UC1.7 aggiungere controlli sui dati inseriti
- [x] UC2.3 no sottocaso di UC2
- [x] UC2.5 rivedere attore??
- [x] UC3 username deve essere univoco e non modificabile
- [x] UC5.1 e sottocasi devono essere in ereditarietà
- [x] UC5.1.2 sorgenti di importazione del progetto
- [x] UC6 rivedere nomi dei casi d'uso che devono identificare un'azione
- [x] UC6.1.1.3 formato di esportazione
- [x] UC6.1.1.4 linguaggi supportati
- [x] UC6.1.4 cos’è un layer? 
- [x] Quali sono le caratteristiche degli oggetti dopo che sono stati creati (classi, relazioni, ecc...?). Prima della modifica si troveranno comunque in uno stato definito.
- [x] UC6.3.1.1 rivedere sotto casi d'uso rispetto eliminazione
- [x] No definito il significato del codice dei requisiti
- [x] Requisiti vincolo: riportare versione browser e piattaforme supportate

Disegni UC da rifare:
- [x] UC3 togliendo UC3.1 UC3.5 e spostando i sottocasi rimanenti
- [x] UC5 inserendo in ereditarietà su UC5.1 gli UC5.1.1 UC5.1.2
- [x] togliere disegno UC5.1
- [x] UC0 modificare UC6
- [x] UC6 modificare titolo e nomi sotto UC6.1 6.2 6.3 6.4
- [x] UC6.1 modificare titolo e  nomi sotto UC6.1.1 6.1.2 6.1.3 6.1.4
- [x] UC6.1.1 modificare titolo 
- [x] UC6.1.2 modificare titolo 
- [x] UC6.1.3 modificare titolo 
- [x] UC6.1.4 modificare titolo 
- [x] UC6.2 modificare titolo e nomi sotto UC6.2.1 6.2.2
- [x] UC6.2.1 modificare titolo 
 - [x] UC6.2.2 modificare titolo
- [x] UC6.3 modificare titolo
- [x] UC6.4 modificare titolo 

Togliere Requisiti tabelle tracciamento:
- [x] UC3.6
- [x] UC3.7
- [x] UC2.3
- [x] UC2.5
Aggiungere Requisiti tabelle tracciamento:
- [x] UC7
- [x] UC7.1

### Aggiornare il diario delle modifiche incrementando il parametro Z (X.Y.Z)

**Comment by massi94** [comment]
Tolto UC3.1 UC3.5 perchè username non può essere modificato, spostati i numeri degli altri sotto casi d'uso. Non esistono più UC3.6 UC3.7

**Comment by Firion711** [comment]
sezione funzionalità del prodotto è stata ESTESA

**Comment by massi94** [comment]
@Firion711 guardi te questo? UC6.3.1.1 rivedere sotto casi d'uso rispetto eliminazione

**Comment by Firion711** [comment]
Sistemato il punto 6.3.1.1 con i sotto-casi spostati come da accordi telefonici

**Comment by Firion711** [comment]
Nella sezione tracciamento fonti - requisiti ( sezione 5.4) compare una pagina vuota prima della tabella. Non son riuscito a sistemare, @massi94 quando puoi prova a darci un occhio
