### ISSUE TITLE
Piano di progetto

### ISSUE THREAD

**Issue by Firion711** [SWEetBIT/SWEDesigner---RR#5]
- Organizzare il documento secondo la _best practice_

- capitolo 3 : la pianificazione che descrivete pare guidata solo dalla produzione dei documenti richiesti in ingresso alle revisioni di progresso, invece che dalle esigenze di sviluppo vere e proprie (come dovrebbe invece derivare dalla scelta di un modello incrementale). ?????

- capitolo 3.2: assumere che l'attività di analisi dei requisiti si concludano con l'ingresso in RR, senza prevedere risorse per correzioni e miglioramenti, è rischiosamente ottimista.

**Comment by Giansalmi** [comment]
Capitolo 3 non è da modificare.
Capitolo 3.2 sistemato.
